### PR TITLE
simultaneous-ctcf-birth-death

### PR DESCRIPTION
**Pull request by gfudenberg**
addresses two issues discussed with @hadirah87 :
- CTCF occupancy is biased if exchange is rapid (since birth & death are done sequentially)
- CTCF occupancy takes a while to equilibrate

Old output showing these issues:
image

New output:
image

The implementation was not particularly elegant... Suggestions most welcome!

Code to reproduce plots
```python
numLEF = 1
N = 100
deathProb = np.zeros((N,))
stalledDeathProb =  np.zeros((N,))
birthArray = np.zeros((N,)); birthArray[1] = 1
pauseProb = np.zeros((N,))
stallProbLeft = np.ones((N,)); 
stallProbRight_init = np.ones((N,));
ctcfDeathProb =  np.zeros((N,)) + .5; 
ctcfBirthProb =  np.zeros((N,)) + .5;

translocator = LEFTranslocatorDynamicBoundary(
    numLEF,
    deathProb,
    stalledDeathProb,
    birthArray,
    pauseProb,
    stallProbLeft,
    stallProbRight_init,
    ctcfDeathProb,
    ctcfBirthProb,
)

num_steps = 100
ctcfs = np.zeros((num_steps, len(stallProbRight_init)))#
ctcfs_left = np.zeros((num_steps, len(stallProbRight_init)))#

for i in range(num_steps):
    ctcfs[i, :] = translocator.stallProbRight
    ctcfs_left[i,:] = translocator.stallProbLeft
    translocator.step()

print(np.mean(ctcfs[:,4]))

plt.plot(np.mean(ctcfs,axis=1))
plt.hlines( ctcfBirthProb/(ctcfBirthProb+ctcfDeathProb) , xmin=0,xmax=num_steps, color='k',lw=0.5)
plt.plot(np.mean(ctcfs_left,axis=1), ls='--')

plt.ylim([0,1])
plt.grid()
```

### CODE REVIEW

**Review by hadirah87 — APPROVED** [review]

**Comment by mtortora** [comment]
Looks good!
I guess we can get rid of the birth/death loops altogether using the following functions (which accept index lists as arguments):
`def ctcf_death_left(self, inds):
       bound_LEFs = np.flatnonzero(self.LEFs[:, 0] == inds)

       self.stalled[bound_LEFs, 0] = 0
       self.stallProbLeft[inds] = 0`

`def ctcf_birth_left(self, inds):
       self.stallProbLeft[inds] = self.stallProbLeft_init[inds]`

I don't know if that would make things cleaner, but it would be slightly more concise/computationally-efficient

**Comment by mtortora** [comment]
Also, since birth and death are two uncorrelated events, they probably should need a separate coin flip

**Comment by mtortora** [comment]
The simultaneous update formalism made me realize that a lot of the loops in the code can be optimized away in numpy.
I don't think I have the permissions to update the PR, but here's a [vectorized version](https://gist.github.com/mtortora/1f998a510db4922b3e31d7d0fed18191) of the dynamic boundary code, also introducing explicit bookkeeping of CTCF states). Let me know what you think @gfudenberg  @hadirah87!

**Comment by gfudenberg** [comment]
oops- hadn't realized you weren't added to this repo @mtortora ! Let me know if you have access now.

Also, it seems like a bunch of the todos in #1  are checked off-- maybe @hadirah87 & you can check which ones are still most relevant?
https://github.com/Fudenberg-Research-Group/dynamic_extrusion_boundaries/issues/1

**Comment by mtortora** [comment]
Perfect! PR should now be updated @gfudenberg 
I've now resolved most of the issues in #1, with the exception of the CTCF position getter (which is already implemented in the multi-state extrusion [repository](https://github.com/mtortora/lattice-translocators)).
The last point I was unclear about is the one re unloading of CTCF -- did you mean that in the case of 'double' site occupancy by left/right CTCFs, unloading one should automatically unload the other? I was under the impression that these could indeed be considered independent events, as multiple CTCFs can in principle coexist in one site.

**Comment by mtortora** [comment]
> perhaps still useful to have equilibrium occupancy initialization passed as a kwarg with default True (e.g. initalize_at_equilibrium_occupancy=True) in case we wanted to start w/ say all CTCFs unbound or bound?

Yes, that's a good point. I got rid of it because it felt somewhat clunky, and I can see the initialization from an equilibrated being a more useful default option in the long run. It could perhaps come in handy for unit tests of equilibration kinetics though, if/when we get around to writing some, so can be kept around as an option

> it also seems that this vectorized version does not allow for stallProbLeft less than 1-- is that a feature that is important to keep or not?

I feel like stallProbs being less than 1 is kind of redundant with dynamic boundaries? It could also be kept as an option, but requires carrying around a copy of the initial stall arrays, so would be a bit less 'clean'

**Comment by gfudenberg** [comment]
> Perfect! PR should now be updated @gfudenberg I've now resolved most of the issues in #1, with the exception of the CTCF position getter (which is already implemented in the multi-state extrusion [repository](https://github.com/mtortora/lattice-translocators)). 

Ah, I think this is a deprecated point if the translocator is in python, then the getter isn't really needed (and we can just grab self.CTCFStateLeft, self.CTCFStateRight. Let's check this off!

> The last point I was unclear about is the one re unloading of CTCF -- did you mean that in the case of 'double' site occupancy by left/right CTCFs, unloading one should automatically unload the other? I was under the impression that these could indeed be considered independent events, as multiple CTCFs can in principle coexist in one site.

Hmm, I was thinking that based on single molecule expts, any individual CTCF could have some chance to pause or block from either direction. I agree that a CTCF binding the forward vs reverse strand should be treated distinctly...

**Comment by mtortora** [comment]
> Hmm, I was thinking that based on single molecule expts, any individual CTCF could have some chance to pause or block from either direction. I agree that a CTCF binding the forward vs reverse strand should be treated distinctly...

I see! Very good point @gfudenberg, as I'm indeed realizing this was improperly implemented in the previous dynamic boundary version (although I don't believe we made use of it). In the static boundary code, this bidirectional stalling of individual sites was implemented via the `backstall`/`facestall` parameters, although only the `facestall` was set to zero upon unbinding, and re-updated upon binding in the dynamic version. This bidirectional stalling is now disabled altogether in the new simultaneous update code, in which `facestall=1` and setting `backstall>0` simply creates extra CTCF sites with opposite orientations in the initial state. It could definitely be good to keep this as an option, but would require bringing back the non-integer stall probabilities

**Pull request merged**
